### ISSUE TITLE
Clock Selector Configuration - HowTo

### ISSUE THREAD

**Issue by jminutaglio** [DDraiman1990/DroidTimeSelection#7]
Ok, a how to:

if using the Clock Selector Configuration, there are no UI controls for "OK" or "CANCEL".

So the use-case here is when you'd want to use the control with accept buttons elsewhere?  or am I missing a config?

ty!

**Comment by DDraiman1990** [comment]
This library is something I made really quickly and without giving it too much thought. Looking at the code now I think I am going to rewrite portions of it to actually be accessible and easy to use instead of fixing tiny bugs. 
Stay tuned cause this library will be in much better shape in the next 1-2 weeks.

**Comment by jminutaglio** [comment]
awesome, I'm excited :)

**Comment by DDraiman1990** [comment]
2.0.0 is now live and should be easier to configure.
